var empty_values="todaymore todayless older1days older7days older15days older30days older60days older90days older120days".split(" ");if(document.all)var browser_ie=!0;else if(document.layers)var browser_nn4=!0;else if(document.layers||!document.all&&document.getElementById)var browser_nn6=!0;
function getObj(a,b){var d,e;b||(b=document);void 0!=a&&0<(d=a.indexOf("?"))&&parent.frames.length&&(b=parent.frames[a.substring(d+1)].document,a=a.substring(0,d));b.getElementById&&(e=b.getElementById(a))&&e.id!=a&&(e=!1);for(d=0;!e&&d<b.forms.length;d++)e=b.forms[d][a];for(d=0;!e&&b.layers&&d<b.layers.length;d++)e=getObj(a,b.layers[d].document);e||(e=b[a])||!b.all||(e=b.all[a]);"string"==typeof e&&(e=null);return e}function replaceAll(a,b,d){return d.replace(new RegExp(escapeRegExp(a),"g"),b)}
function replaceUploadSize(){var a=document.getElementById("key_upload_maxsize").value,a=("'"+a+"'").replace(/000000/g,""),a=a.replace(/'/g,"");document.getElementById("key_upload_maxsize").value=a}
function vtlib_field_help_show_this(a,b){var d=$("vtlib_fieldhelp_div"),e=document.getElementById("helpInfo").value;d?d.show():(d=document.createElement("div"),d.id="vtlib_fieldhelp_div",d.className="dvtSelectedCell",d.style.position="absolute",d.style.width="150px",d.style.padding="4px",d.style.fontWeight="normal",document.body.appendChild(d),d=$("vtlib_fieldhelp_div"),Event.observe(d,"mouseover",function(){$("vtlib_fieldhelp_div").show()}),Event.observe(d,"mouseout",vtlib_field_help_hide));d.innerHTML=
e;fnvshobj(a,"vtlib_fieldhelp_div")}var gcurrepfolderid=0;function trimfValues(a){return a.split(":")[4]}
function vtereports_updatefOptions(a,b,d){jQuery(document).ready(function(){var e=[];e.V="e n s ew c k isn isnn".split(" ");e.N="e n l g m h isn isnn".split(" ");e.SUM="e n l g m h isn isnn".split(" ");e.AVG="e n l g m h isn isnn".split(" ");e.MIN="e n l g m h isn isnn".split(" ");e.MAX="e n l g m h isn isnn".split(" ");e.COUNT="e n l g m h isn isnn".split(" ");e.T="e n l g m h bw b a isn isnn".split(" ");e.I="e n l g m h isn isnn".split(" ");e.C=["e","n","isn","isnn"];e.D="e n l g m h bw b a isn isnn".split(" ");
e.NN="e n l g m h isn isnn".split(" ");e.E="e n s ew c k isn isnn".split(" ");var f=[];f.S="e n s ew c k isn isnn".split(" ");var g=[];g.e=app.vtranslate("EQUALS");g.n=app.vtranslate("NOT_EQUALS_TO");g.s=app.vtranslate("STARTS_WITH");g.ew=app.vtranslate("ENDS_WITH");g.c=app.vtranslate("CONTAINS");g.k=app.vtranslate("DOES_NOT_CONTAINS");g.l=app.vtranslate("LESS_THAN");g.g=app.vtranslate("GREATER_THAN");g.m=app.vtranslate("LESS_OR_EQUALS");g.h=app.vtranslate("GREATER_OR_EQUALS");g.bw=app.vtranslate("BETWEEN");
g.b=app.vtranslate("BEFORE");g.a=app.vtranslate("AFTER");g.isn=app.vtranslate("IS_NULL");g.isnn=app.vtranslate("IS_NOT_NULL");var h=document.getElementById(b);if(h){var k,m=h.options[h.selectedIndex],l=a.options[a.selectedIndex];if(null!=l.value&&0!=l.value.length){k=trimfValues(l.value);var n=JSON.parse(document.getElementById("sel_fields").value),p=document.getElementById("std_filter_columns").value,p="undefined"!=typeof p&&""!=p?p.split("<%jsstdjs%>"):[],r=document.getElementById("std_filter_criteria").value;
if(-1<p.indexOf(l.value)){e=JSON.parse(r);f=h.length;for(nLoop=0;nLoop<f;nLoop++)h.remove(0);h.options[0]=new Option("None","");var f=1,q;for(q in e)h.options[f]=new Option(e[q],q),f++;for(q=0;q<h.length;q++)h.options[q].value==d&&(h.options[q].selected=!0)}else var t=n[l.value]?f.S:e[k];if(null!=t){q=h.length;for(nLoop=0;nLoop<q;nLoop++)h.remove(0);h.options[0]=new Option("None","");""==l.value&&(h.options[0].selected=!0);for(l=0;l<t.length;l++)null!=g[t[l]]&&(q=new Option(g[t[l]],t[l]),h.options[l+
1]=q,null!=m&&m.value==q.value||q.value==d)&&(q.selected=!0)}}else{q=h.length;for(nLoop=0;nLoop<q;nLoop++)h.remove(0);h.options[0]=new Option("None","");""==l.value&&(h.options[0].selected=!0)}}})}function set_cookie(a,b,d,e,f,g,h,k){a=a+"="+escape(b);d&&(a+="; expires="+(new Date(d,e,f)).toGMTString());g&&(a+="; path="+escape(g));h&&(a+="; domain="+escape(h));k&&(a+="; secure");document.cookie=a}function get_cookie(a){return(a=document.cookie.match(a+"=(.*?)(;|$)"))?unescape(a[1]):null}
function delete_cookie(a){var b=new Date;b.setTime(b.getTime()-1);document.cookie=a+("=; expires="+b.toGMTString())}function goToURL(a){document.location.href=a}function invokeAction(a){"newReport"==a?goToURL("?module=VTEReports&action=NewReport0&return_module=VTEReports&return_action=index"):goToURL("/crm/ScheduleReport.do?step=showAllSchedules")}
function verify_data(a){var b=!1,d="";""==trim(a.folderName.value)&&(b=!0,d+="\nFolder Name");return 1==b?(alert(app.vtranslate("MISSING_FIELDS")+d),!1):!0}function setObjects(){getObj("availList");getObj("selectedColumns");getObj("moveup_link");getObj("moveup_disabled");getObj("movedown_link");getObj("movedown_disabled")}
function addColumn(a){var b="selectedColumnsRel"==a?getObj("selectedColumns"):"selectedQFColumnsRel"==a?getObj("selectedQFColumns"):"selectedSummaries"==a?getObj("selectedSummaries"):getObj(a);for(i=0;i<b.length;i++)b.options[i].selected=!1;"selectedColumns"==a?addColumnStep1():"selectedColumnsRel"==a?addColumnStep3():"selectedQFColumnsRel"==a?addColumnStep4():"selectedSummaries"==a?addColumnStep5():addColumnStep2()}
function addColumnStep1(){var a=getObj("availList"),b=getObj("selectedColumns"),d=document.getElementById("availModules"),e=d.options[d.selectedIndex].text,d=d.options[d.selectedIndex].value,f=document.getElementById("primarymodule").options[document.getElementById("primarymodule").selectedIndex].value;d!=f&&(e=e.replace("- ",""));if(-1<a.options.selectedIndex)for(i=0;i<a.length;i++)if(1==a.options[i].selected){d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.options[i].value){var d=!0,g=b.options[j];
break}1!=d?(d=document.createElement("OPTION"),d.value=a.options[i].value,d.text=a.options[i].text+" ["+e+"]",b.appendChild(d),d.selected=!0):g.selected=!0;a.options[i].selected=!1;addColumnStep1()}a=getObj("SortByColumn").value;getObj("SortByColumn").innerHTML="<option value='none'>"+none_lang+"</option>";getObj("SortByColumn").innerHTML+=b.innerHTML;getObj("SortByColumn").value=a}
function addColumnStep2(){var a=getObj("availQFList"),b=getObj("selectedQFColumns");if(-1<a.options.selectedIndex)for(i=0;i<a.length;i++)if(1==a.options[i].selected){var d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.options[i].value){var d=!0,e=b.options[j];break}if(1!=d){d=document.createElement("OPTION");d.value=a.options[i].value;if(browser_ie)d.innerText=a.options[i].innerText;else if(browser_nn4||browser_nn6)d.text=a.options[i].text;b.appendChild(d);d.selected=!0}else e.selected=!0;a.options[i].selected=
!1;addColumnStep2()}}function addColumnStep3(){var a=getObj("selectedColumns"),b=getObj("SortByColumn").value;getObj("SortByColumn").innerHTML="<option value='none'>"+none_lang+"</option>";getObj("SortByColumn").innerHTML+=a.innerHTML;getObj("SortByColumn").value=b}
function addColumnStep4(){var a=getObj("availQFList2"),b=getObj("selectedQFColumns");if(-1<a.options.selectedIndex)for(i=0;i<a.length;i++)if(1==a.options[i].selected){var d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.options[i].value){var d=!0,e=b.options[j];break}if(1!=d){d=document.createElement("OPTION");d.value=a.options[i].value;if(browser_ie)d.innerText=a.options[i].innerText;else if(browser_nn4||browser_nn6)d.text=a.options[i].text;b.appendChild(d);d.selected=!0}else e.selected=!0;a.options[i].selected=
!1;addColumnStep4()}}
function addColumnStep5(){var a=getObj("availListSum"),b=getObj("selectedSummaries");if(-1<a.options.selectedIndex)for(i=0;i<a.length;i++)if(1==a.options[i].selected){var d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.options[i].value){var d=!0,e=b.options[j];break}if(1!=d){if("none"!=a.options[i].value){d=document.createElement("OPTION");d.value=a.options[i].value;var f=document.getElementById("SummariesModules"),f=f.options[f.selectedIndex].text;"- "==f.substring(0,2)&&(f=f.substring(2));
d.text=a.options[i].text+" ("+f+")";addToSummSortOrder(a.options[i]);b.appendChild(d)}}else e.selected=!0;a.options[i].selected=!1;addColumnStep5()}}function setSelSummSortOrder(a){var b=getObj("summaries_orderby_column");if(b){for(j=0;j<b.length;j++)if(b.options[j].value==a){var d=j,e=b.options[j].value;b.options[j].selected=!0;break}document.getElementById("summaries_orderby_columnString").value=e;"undefined"!=typeof b.options[d]&&(b.options[d].selected=!0)}}
function delSummSortOrder(a){var b=getObj("summaries_orderby_column");for(j=0;j<b.options.length;j++)a.value==b.options[j].value&&b.remove(j)}function delSortOrder(a){var b=getObj("SortByColumn");for(j=0;j<b.options.length;j++)a.value==b.options[j].value&&b.remove(j)}
function addToSummSortOrder(a){var b=getObj("summaries_orderby_column");if("undefined"!=typeof b){var d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.value){d=!0;break}1!=d&&(d=document.createElement("OPTION"),"none"!=a.value&&(d.value=a.value,d.text=a.text,b.appendChild(d)))}}
function addToSortOrder(a){var b=getObj("SortByColumn");if("undefined"!=typeof b){var d=!1;for(j=0;j<b.length;j++)if(b.options[j].value==a.value){d=!0;break}1!=d&&(d=document.createElement("OPTION"),"none"!=a.value&&(d.value=a.value,d.text=a.text,b.appendChild(d)))}}
function selectedColumnClick(a){var b="",d=!1;if(-1<a.selectedIndex)for(var e=0;e<a.options.length;++e)1==a.options[e].selected&&1==a.options[e].disabled&&(b=b+a.options[e].text+",",d=!0,a.options[e].selected=!1);return d?(b=b.substr(0,b.length-1),alert(app.vtranslate("NOT_ALLOWED_TO_EDIT_FIELDS")+"\n"+b),!1):!0}
function delColumn(a){var b=getObj(a);if(-1<b.options.selectedIndex)for(i=0;i<b.options.length;i++)if(1==b.options[i].selected){delSummSortOrder(b.options[i]);if("selectedColumns"==a){var d=getObj("SortByColumn");for(j=0;j<d.options.length;j++)b.options[i].value==d.options[j].value&&d.remove(j)}b.remove(i);delColumn(a)}}function hasOptions(a){return null!=a&&null!=a.options?!0:!1}
function swapOptions(a,b,d){a=a.options;var e=a[b].selected,f=a[d].selected,g=new Option(a[b].text,a[b].value,a[b].defaultSelected,a[b].selected),h=new Option(a[d].text,a[d].value,a[d].defaultSelected,a[d].selected);a[b]=h;a[d]=g;a[b].selected=f;a[d].selected=e}function moveUp(a){a=getObj(a);if(hasOptions(a))for(var b=0;b<a.options.length;b++)a.options[b].selected&&0!=b&&!a.options[b-1].selected&&(swapOptions(a,b,b-1),a.options[b-1].selected=!0)}
function moveDown(a){a=getObj(a);if(hasOptions(a))for(var b=a.options.length-1;0<=b;b--)a.options[b].selected&&b!=a.options.length-1&&!a.options[b+1].selected&&(swapOptions(a,b,b+1),a.options[b+1].selected=!0)}
function disableMove(){var a=getObj("selectedColumns"),b=0;for(i=0;i<a.options.length;i++)1==a.options[i].selected&&b++;1<b?(moveupLinkObj.style.display=movedownLinkObj.style.display="none",moveupDisabledObj.style.display=movedownDisabledObj.style.display="block"):(moveupLinkObj.style.display=movedownLinkObj.style.display="block",moveupDisabledObj.style.display=movedownDisabledObj.style.display="none")}function hideTabs(){}
function showSaveDialog(){window.open("index.php?module=VTEReports&action=SaveReport","Save_Report","width=550,height=350,top=20,left=20;toolbar=no,status=no,menubar=no,directories=no,resizable=yes,scrollbar=no")}
function saveAndRunReport(){var a=getObj("primarymodule"),b=trim(a.value);document.NewReport.report_primarymodule.value=b;var a=getObj("selectedColumns"),d=getObj("selectedSummaries");if(0==a.options.length&&0==d.options.length){var e={title:app.vtranslate("COLUMNS_CANNOT_BE_EMPTY"),type:"error"};Vtiger_Helper_Js.showPnotify(e);return!1}d="";a=document.getElementById("all_related_modules").value;if(""!=a)for(var f=a.split(":"),a=0;a<=f.length-1;a++)b=document.getElementById("relmodule_"+f[a]),b.checked&&
(d+=b.value+":");document.NewReport.secondarymodule.value=d;for(var d="account_id contactid contact_id product_id parent_id campaignid potential_id assigned_user_id1 quote_id accountname salesorder_id vendor_id time_start time_end lastname".split(" "),g=vt_getElementsByName("tr","conditionColumn"),h=[],k=JSON.parse(document.getElementById("sel_fields").value),a=0;a<g.length;a++){var f=g[a].getAttribute("id"),b=f.split("_"),f=b[1],m=b[2];ctype="0"!=f?"f":"g";var l=ctype+"col"+m,n=getObj(l),b=n.value,
p=n.selectedIndex,r=n.options[p].text;if("none"!=n.options[p].value){var q=ctype+"op"+m,n=getObj(q),n=n.value,p=ctype+"val"+m,t=getObj(p),u=t.value,e=ctype+"val_ext"+m,v=getObj(e);v&&(extendedValue=v.value);var t=ctype+"con"+m,x=getObj(t),t="";x&&(t=x.value);if(1<g.length&&(!emptyCheckVte(l," Column ","text")||!emptyCheckVte(q,r+" Option","text")))return!1;l=b.split(":");q=document.getElementById("std_filter_columns").value;if(-1<("undefined"!=typeof q&&""!=q?q.split("<%jsstdjs%>"):[]).indexOf(b)){if("custom"==
n&&!emptyCheckVte("jscal_field_sdate"+m," Column ","text")||"custom"==n&&!emptyCheckVte("jscal_field_edate"+m," Column ","text"))return!1;r=document.getElementById("jscal_field_sdate"+m).value;u=document.getElementById("jscal_field_edate"+m).value;u=r+"<;@STDV@;>"+u}else if(-1==d.indexOf(l[3])){if("T"==l[4]){if(q=u.split(" "),!re_dateValidate(q[0],r+" (Current User Date Time Format)","OTH")||1<q.length&&!re_patternValidate(q[1],r+" (Time)","TIMESECONDS"))return!1}else if("D"==l[4]){if(!dateValidate(p,
r+" (Current User Date Format)","OTH")||v&&!dateValidate(e,r+" (Current User Date Format)","OTH"))return!1}else if("I"==l[4]){if(!intValidate(p,r+" (Integer Criteria)"+a))return!1}else if("N"==l[4]){if(!numValidate(p,r+" (Number) ","any",!0))return!1}else if("E"==l[4]&&!patternValidate(p,r+" (Email Id)","EMAIL"))return!1;k[b]&&(u=jQuery("#s_fval"+m).val())}"C"==l[4]&&("1"==u?u=getObj(p).value="yes":"0"==u&&(u=getObj(p).value="no"));v&&null!=extendedValue&&""!=extendedValue&&(u=u+","+extendedValue);
h[m]={groupid:f,columnname:b,comparator:n,value:u,column_condition:t}}}jQuery("#advft_criteria").value=JSON.stringify(h);f=vt_getElementsByName("div","conditionGroup");b=[];for(a=0;a<f.length;a++)g=f[a].getAttribute("id").split("_")[1],h=getObj("gpcon"+g),k="",h&&(k=h.value),b[g]={groupcondition:k};jQuery("#advft_criteria_groups").value=JSON.stringify(b);g=vt_getElementsByName("tr","groupconditionColumn");h=[];for(a=0;a<g.length;a++)if(f=g[a].getAttribute("id"),b=f.split("_"),f=b[1],m=b[2],ctype=
"0"!=f?"f":"g",l=ctype+"groupcol"+m,n=getObj(l),b=n.value,p=n.selectedIndex,r=n.options[p].text,"none"!=n.options[p].value){q=ctype+"groupop"+m;n=getObj(q);n=n.value;p=ctype+"groupval"+m;t=getObj(p);u=t.value;t=ctype+"groupcon"+m;x=getObj(t);t="";x&&(t=x.value);if(1<g.length&&(!emptyCheckVte(l," Column ","text")||!emptyCheckVte(q,r+" Option","text")))return!1;l=b.split(":");if(-1==d.indexOf(l[3]))if("T"==l[4]){if(q=u.split(" "),!re_dateValidate(q[0],r+" (Current User Date Time Format)","OTH")||1<
q.length&&!re_patternValidate(q[1],r+" (Time)","TIMESECONDS"))return!1}else if("D"==l[4]){if(!dateValidate(p,r+" (Current User Date Format)","OTH")||v&&!dateValidate(e,r+" (Current User Date Format)","OTH"))return!1}else if("I"==l[4]){if(!intValidate(p,r+" (Integer Criteria)"+a))return!1}else if("N"==l[4]){if(!numValidate(p,r+" (Number) ","any",!0))return!1}else if("E"==l[4]&&!patternValidate(p,r+" (Email Id)","EMAIL"))return!1;"C"==l[4]&&("1"==u?u=getObj(p).value="yes":"0"==u&&(u=getObj(p).value=
"no"));v&&null!=extendedValue&&""!=extendedValue&&(u=u+","+extendedValue);h[m]={groupid:f,columnname:b,comparator:n,value:u,column_condition:t}}jQuery("#groupft_criteria").value=JSON.stringify(h);formSelectedColumnString();formSelectedSummariesString();getCurl();getLabelsurl();return!0}
function formSelectedSummariesString(){var a="";jQuery("tr.drag_to_sort_order").each(function(){a+=jQuery(this).data("id")+";"});null!==document.getElementById("selectedSummariesString")&&(document.getElementById("selectedSummariesString").value=a)}function formSelectedColumnString(){var a="";jQuery("tr.drag_to_sort_order").each(function(){a+=jQuery(this).data("id")+";"});null!==document.getElementById("selectedColumnsString")&&(document.getElementById("selectedColumnsString").value=a)}
function nextStepVte(){a+=1;2==a&&(a+=2);var a;12!=a?changeSteps4U(a):changeSteps()}
function setSTDFilter(a){var b;b="action=VTEReportsAjax&mode=ajax&file=ChangeSteps&module=VTEReports&step=getStdFilter";a&&""!=a&&(b+="&selectedStdFilter="+a);a=document.getElementById("record")?document.getElementById("record").value:"";b+="&record="+a;"text"==document.getElementById("primarymodule").type?a=document.getElementById("primarymodule").value:""!=document.getElementById("primarymodule")&&"hidden"!=document.getElementById("primarymodule").type?(a=document.getElementById("primarymodule").selectedIndex,
a=document.getElementById("primarymodule").options[a].value):a="";b=b+("&reportmodule="+a)+("&primarymodule="+a);if("undefined"!=typeof document.NewReport.stdDateFilterField&&""!=document.NewReport.stdDateFilterField){a=document.NewReport.stdDateFilterField;var d=a.length;for(nLoop=0;nLoop<d;nLoop++)a.remove(0);a.options[0]=new Option("None","");a.options[0].selected=!0}a=document.getElementById("current_action")?document.getElementById("current_action").value:"";""!=a&&"resultGenerate"==a?jQuery.post("index.php?"+
b,function(a){}).done(function(a){var b=a.split("#@!@#");a=JSON.parse(b[0]);var b=b[1],d;for(d in a)if(a.hasOwnProperty(d)){option=a[d];var e=document.createElement("OPTION");e.value=option.value;option.value==b&&(e.selected=!0);e.appendChild(document.createTextNode(option.text));document.NewReport.stdDateFilterField.appendChild(e)}}):new Ajax.Request("index.php",{queue:{position:"end",scope:"command"},method:"post",postBody:b,onComplete:function(a){var b=a.responseText.split("#@!@#");a=JSON.parse(b[0]);
var b=b[1],d;for(d in a)if(a.hasOwnProperty(d)){option=a[d];var e=document.createElement("OPTION");e.value=option.value;option.value==b&&(e.selected=!0);e.appendChild(document.createTextNode(option.text));document.NewReport.stdDateFilterField.appendChild(e)}}})}
function getQFurl(){var a,b="";a=document.getElementsByTagName("input");for(var d=0;d<a.length;d++)"checkbox"==a[d].type&&(Control_Data=a[d].name.split(":"),"qf"==Control_Data[0]&&1==a[d].checked&&(""!=b&&(b+="$_@_$"),b+=a[d].name));return document.getElementById("qf_to_go").value=b}
function getCurl(){var a,b="";a=document.getElementsByTagName("input");for(var d=0;d<a.length;d++)"checkbox"==a[d].type&&(Control_Data=a[d].name.split(":"),"cb"==Control_Data[0]&&1==a[d].checked&&(""!=b&&(b+="$_@_$"),b+=a[d].name));return document.getElementById("curl_to_go").value=b}
function getLabelsurl(){var a,b="";a=document.getElementsByTagName("input");for(var d=0;d<a.length;d++)if(a[d]){var e=a[d].id;-1<e.indexOf("_lLbLl_")&&-1==e.indexOf("hidden_")&&(""!=b&&(b+="$_@_$"),e=a[d].id+"_lLGbGLl_"+a[d].value,e=replaceAll("&","@AMPKO@",e),b+=e)}return document.getElementById("labels_to_go").value=b}
function setRelModules(a){var b=document.NewReport.relatedmodules.value.split(":"),d=[];if(inMyArray(b,a))for(i=0;i<b.length;i++)b[i]!=a&&d.push(b[i]);else""==b?b[0]=a:b.push(a),d=b;document.NewReport.relatedmodules.value=d.join(":");return!1}function inMyArray(a,b){var d;for(d=0;d<a.length;d++)if(a[d]==b)return!0;return!1}
function changeSteps1(){if("none"!=getObj("step4").style.display){for(var a="account_id contactid contact_id product_id parent_id campaignid potential_id assigned_user_id1 quote_id accountname salesorder_id vendor_id time_start time_end lastname".split(" "),b=vt_getElementsByName("tr","conditionColumn"),d=[],e=0;e<b.length;e++){var f=b[e].getAttribute("id").split("_"),g=f[1],f=f[2],h="fcol"+f,k=getObj(h),m=trim(k.value),k=k.options[k.selectedIndex].text,l="fop"+f,n=getObj(l),n=trim(n.value),p="fval"+
f,r=getObj(p),r=trim(r.value),q="fval_ext"+f,t=getObj(q);t&&(extendedValue=trim(t.value));var u=getObj("fcon"+f),v="";u&&(v=trim(u.value));if(!emptyCheckVte(h," Column ","text")||!emptyCheckVte(l,k+" Option","text"))return!1;h=m.split(":");if(-1==a.indexOf(h[3]))if("T"==h[4]){if(l=r.split(" "),!re_dateValidate(l[0],k+" (Current User Date Time Format)","OTH")||1<l.length&&!re_patternValidate(l[1],k+" (Time)","TIMESECONDS"))return!1}else if("D"==h[4]){if(!dateValidate(p,k+" (Current User Date Format)",
"OTH")||t&&!dateValidate(q,k+" (Current User Date Format)","OTH"))return!1}else if("I"==h[4]){if(!intValidate(p,k+" (Integer Criteria)"+e))return!1}else if("N"==h[4]){if(!numValidate(p,k+" (Number) ","any",!0))return!1}else if("E"==h[4]&&!patternValidate(p,k+" (Email Id)","EMAIL"))return!1;"C"==h[4]&&("1"==r?r=getObj(p).value="yes":"0"==r&&(r=getObj(p).value="no"));t&&null!=extendedValue&&""!=extendedValue&&(r=r+","+extendedValue);d[f]={groupid:g,columnname:m,comparator:n,value:r,column_condition:v}}$("advft_criteria").value=
JSON.stringify(d);a=vt_getElementsByName("div","conditionGroup");b=[];for(e=0;e<a.length;e++)d=a[e].getAttribute("id").split("_")[1],g=getObj("gpcon"+d),f="",g&&(f=trim(g.value)),b[d]={groupcondition:f};$("advft_criteria_groups").value=JSON.stringify(b);e=getObj("startdate");a=getObj("enddate");if(""!=e.value||""!=a.value)if(!dateValidate("startdate","Start Date","D")||!dateValidate("enddate","End Date","D")||!dateComparison("startdate","Start Date","enddate","End Date","LE"))return!1}if("none"!=
getObj("step12").style.display)saveAndRunReport();else for(e=0;e<divarray.length;e++)if("none"!=getObj(divarray[e]).style.display){1==e&&0==selectedColumnsObj.options.length&&deleteColumnRow(1,0);"step4"==divarray[e]&&(document.getElementById("next").value=finish_text);hide(divarray[e]);show(divarray[e+1]);tableid=divarray[e]+"label";newtableid=divarray[e+1]+"label";getObj(tableid).className="dvtUnSelectedCell";getObj(newtableid).className="dvtSelectedCell";break}}
function changeStepsback1(){if("none"!=getObj("step1").style.display)document.NewReport.action.value="NewReport0",document.NewReport.submit();else for(i=0;i<divarray.length;i++)if("none"!=getObj(divarray[i]).style.display){document.getElementById("next").value=next_text+">";hide(divarray[i]);show(divarray[i-1]);tableid=divarray[i]+"label";newtableid=divarray[i-1]+"label";getObj(tableid).className="settingsTabList";getObj(newtableid).className="settingsTabSelected";break}}
function changeSteps(a){a&&""!=a||(a="Save&Run");if(""==document.getElementById("reportname").value)return a={title:app.vtranslate("MISSING_REPORT_NAME"),text:data.message},Vtiger_Helper_Js.showPnotify(a),jQuery("#reportname").focus(),!1;if(1==getObj("isReportScheduled").checked){var b=getObj("selectedRecipients");if(0==b.options.length)return a={title:app.vtranslate("RECIPIENTS_CANNOT_BE_EMPTY"),type:"error"},Vtiger_Helper_Js.showPnotify(a),!1;for(var d=[],e=[],f=[],g=[],h=0;h<b.options.length;h++){var k=
b.options[h].value.split("::");"users"==k[0]?d.push(k[1]):"groups"==k[0]?e.push(k[1]):"roles"==k[0]?f.push(k[1]):"rs"==k[0]&&g.push(k[1])}h=JSON.stringify({users:d,groups:e,roles:f,rs:g});document.NewReport.selectedRecipientsString.value=h;h=JSON.stringify({scheduletype:document.NewReport.scheduledType.value,month:document.NewReport.scheduledMonth.value,date:document.NewReport.scheduledDOM.value,day:document.NewReport.scheduledDOW.value,time:document.NewReport.scheduledTime.value});document.NewReport.scheduledIntervalString.value=
h;b="";c=document.getElementsByTagName("input");for(var h=0;h<c.length;h++)"checkbox"==c[h].type&&(Control_Data=c[h].name.split(":"),"cb"==Control_Data[0]&&1==c[h].checked&&(""!=b&&(b+="$_@_$"),b+=c[h].name));document.NewReport.curl_to_go.value=b}getUpSelectedSharing();""!=a&&(document.getElementById("SaveType").value=a);saveAndRunReport()&&document.NewReport.submit()}
function changeStepsback(){if(1!=actual_step){var a=actual_step-1;3==a&&(a-=2);changeSteps4U(a);1==a&&(document.getElementById("back_rep_top").disabled=!0)}}function editReport(a){document.location.href="index.php?module=VTEReports&action=NewReport&record="+a+"&mode=edit"}function CreateReport(a){document.location.href="index.php?module=VTEReports&action=NewReport&folder="+gcurrepfolderid+"&reportmodule="+a+"&primarymodule="+a+"&mode=create"}
function fnPopupWin(a){window.open(a,"ReportWindow","width=790px,height=630px,scrollbars=yes")}
function re_dateValidate(a,b,d){if(0==re_patternValidate(a,b,"DATE"))return!1;a=a.replace(/^\s+/g,"").replace(/\s+$/g,"");var e=splitDateVal(a);a=e[0];var f=e[1],e=e[2];if(1>a||31<a||1>f||12<f||1>e||1E3>e||2==f&&29<a||2==f&&28<a&&0!=e%4)return alert(app.vtranslate("ENTER_VALID")+b),!1;switch(parseInt(f)){case 2:case 4:case 6:case 9:case 11:if(30<a)return alert(app.vtranslate("ENTER_VALID")+b),!1}var g=new Date,h=new Date;h.setYear(e);h.setMonth(f-1);h.setDate(a);return"OTH"!=d?compareDates(h,b,g,
"current date",d)?!0:!1:!0}function re_patternValidate(a,b,d){if("DATE"==d.toUpperCase())switch(userDateFormat){case "yyyy-mm-dd":var e=/^\d{4}(-)\d{1,2}\1\d{1,2}$/;break;case "mm-dd-yyyy":case "dd-mm-yyyy":e=/^\d{1,2}(-)\d{1,2}\1\d{4}$/}"TIMESECONDS"==d.toUpperCase()&&(e=/^([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9])$/);if(e.test(a))return!0;alert(app.vtranslate("ENTER_VALID")+b);return!1}
function standardFilterDisplay(){var a=document.getElementById("stdDateFilterField");document.getElementById("stdDateFilterField")&&(0>=a.options.length||-1<a.selectedIndex&&"Not Accessible"==a.options[a.selectedIndex].value?(getObj("stdDateFilter").disabled=!0,getObj("startdate").disabled=!0,getObj("enddate").disabled=!0,getObj("jscal_trigger_date_start").style.visibility="hidden",getObj("jscal_trigger_date_end").style.visibility="hidden"):(getObj("stdDateFilter").disabled=!1,getObj("startdate").disabled=
!1,getObj("enddate").disabled=!1,getObj("jscal_trigger_date_start").style.visibility="visible",getObj("jscal_trigger_date_end").style.visibility="visible"))}
function updateRelFieldOptions(a,b){jQuery(document).ready(function(){var d=document.getElementById(b);if(d){var e=null,f=d.options[d.selectedIndex],g=a.options[a.selectedIndex],h=JSON.parse(document.getElementById("sel_fields").value),k=b.split("val_")[1],m=document.getElementById("fop"+k);if(!h[g.value]||"e"!=m.options[m.selectedIndex].value&&"n"!=m.options[m.selectedIndex].value)if(document.getElementById("node3span"+k+"_ajx").innerHTML="",jQuery("#node3span"+k+"_st").css("display","block"),jQuery("#node3span"+
k+"_ajx").css("display","none"),jQuery("#node3span"+k+"_djx").css("display","none"),"isn"!=m.options[m.selectedIndex].value&&"isnn"!=m.options[m.selectedIndex].value||jQuery("#fval"+k).val(""),null!=g.value&&0!=g.value.length){if(e=trimfValues(g.value),ops=rel_fields[e],e=0,null!=ops){e=d.length;for(nLoop=0;nLoop<e;nLoop++)d.remove(0);d.options[0]=new Option("None","");""==g.value&&(d.options[0].selected=!0);for(var e=1,l=0;l<ops.length;l++){var n=ops[l].split("::"),p=n[1];null!=p&&(n=new Option(p,
n[0]),d.options[l+e]=n,null!=f&&f.value==n.value&&(n.selected=!0))}}}else{e=d.length;for(nLoop=0;nLoop<e;nLoop++)d.remove(0);d.options[0]=new Option("None","");""==g.value&&(d.options[0].selected=!0)}else d=document.getElementById("fval"+k).value,document.getElementById("current_action")&&document.getElementById("current_action"),f={module:"VTEReports",action:"IndexAjax",mode:"getFilterColHtml",sel_fields:JSON.stringify(h),sfield_name:"fval"+k,record:getReportRecordID(),currField:g.value},"undefined"!=
typeof d&&""!=d&&(f.r_sel_fields=d),AppConnector.request({type:"POST",url:"index.php",dataType:"html",data:f}).then(function(a){var b=jQuery("#node3span"+k+"_ajx");b.html(a);b.css("display","block");jQuery("#node3span"+k+"_st").css("display","none");jQuery("#node3span"+k+"_djx").css("display","none");app.changeSelectElementView(b);app.showSelect2ElementView(b.find("select.select2"))})}d=jQuery("#std_filter_columns").val();"undefined"!=typeof d&&""!=d&&(-1<d.split("<%jsstdjs%>").indexOf(a.value)?(d=
document.getElementById("fval"+k).value,getFilterDateHtml(k,d)):(document.getElementById("node3span"+k+"_djx").innerHTML="",!h[g.value]||"e"!=m.options[m.selectedIndex].value&&"n"!=m.options[m.selectedIndex].value?(document.getElementById("node3span"+k+"_ajx").style.display="none",document.getElementById("node3span"+k+"_st").style.display="block"):(document.getElementById("node3span"+k+"_ajx").style.display="block",document.getElementById("node3span"+k+"_st").style.display="none"),document.getElementById("node3span"+
k+"_djx").style.display="none"))})}
function getFilterDateHtml(a,b){document.getElementById("node3span"+a+"_st");getReportRecordID();var d={mode:"getFilterDateHtml",columnIndex:a,record:getReportRecordID()};"undefined"!=typeof b&&""!=b&&(d.r_sel_fields=b);if("undefined"!=typeof document.getElementById("fop"+a)){var e=document.getElementById("fop"+a).value;d.fop_type=e}AppConnector.request({type:"POST",url:"index.php?module=VTEReports&action=IndexAjax",dataType:"html",data:d}).then(function(b){document.getElementById("node3span"+a+"_djx").innerHTML=
b;document.getElementById("node3span"+a+"_st").style.display="none";document.getElementById("node3span"+a+"_ajx").style.display="none";document.getElementById("fval"+a).value="";document.getElementById("node3span"+a+"_djx").style.display="block";if("custom"==e){b=document.getElementById("fop"+a);b=b.options[b.selectedIndex].value;var d=document.getElementById("jscal_field_sdate"+a),f=document.getElementById("jscal_field_edate"+a),k=document.getElementById("jscal_trigger_sdate"+a),m=document.getElementById("jscal_trigger_edate"+
a);showDateRange(d,f,k,m,b);app.registerEventForDateFields("#jscal_field_sdate_val_"+a);app.registerEventForDateFields("#jscal_field_edate_val_"+a)}})}function AddFieldToFilter(a,b){""==trim(document.getElementById("fval"+a).value)?document.getElementById("fval"+a).value=document.getElementById("fval_"+a).value:document.getElementById("fval"+a).value=document.getElementById("fval"+a).value+","+document.getElementById("fval_"+a).value}
function fnLoadRepValues(a,b,d,e){document.getElementById(d).style.display="block";document.getElementById(e).style.display="none";document.getElementById(a).className="dvtSelectedCell";document.getElementById(b).className="dvtUnSelectedCell"}function vt_getElementsByName(a,b){for(var d=document.getElementsByTagName(a),e=[],f=0;f<d.length;f++)d.item(f).getAttribute("name")==b&&e.push(d.item(f));return e}
function formSelectQFColumnString(){var a="",b=getObj("selectedQFColumns");for(i=0;i<b.options.length;i++)a+=b.options[i].value+";";document.NewReport.selectedQFColumnsString.value=a}function uncheckAll(a){a=document.getElementById(a);for(var b=0;b<a.length;b++)a.options[b].selected=!1}function checkAll(a){selObj=document.getElementById(a);for(a=0;a<selObj.length;a++)selObj.options[a].selected=!0}
function CreateCustomReport(a){document.location.href="index.php?module=VTEReports&action=NewCustomReport&folder="+gcurrepfolderid+"&reporttype="+a+"&mode=create"}function editCustomReport(a,b){document.location.href="index.php?module=VTEReports&action=NewCustomReport&record="+a+"&reporttype="+b+"&mode=edit"}
function setRelModules(a){var b=document.NewReport.relatedmodules.value.split(":"),d=[];if(inMyArray(b,a))for(i=0;i<b.length;i++)b[i]!=a&&d.push(b[i]);else""==b?b[0]=a:b.push(a),d=b;document.NewReport.relatedmodules.value=d.join(":");return!1}
function setScheduleOptions(){switch(document.getElementById("scheduledType").value){case "0":case "1":document.getElementById("scheduledMonthSpan").style.display="none";document.getElementById("scheduledDOMSpan").style.display="none";document.getElementById("scheduledDOWSpan").style.display="none";document.getElementById("scheduledTimeSpan").style.display="inline";break;case "2":document.getElementById("scheduledMonthSpan").style.display="none";document.getElementById("scheduledDOMSpan").style.display=
"none";document.getElementById("scheduledDOWSpan").style.display="none";document.getElementById("scheduledTimeSpan").style.display="inline";break;case "3":case "4":document.getElementById("scheduledMonthSpan").style.display="none";document.getElementById("scheduledDOMSpan").style.display="none";document.getElementById("scheduledDOWSpan").style.display="inline";document.getElementById("scheduledTimeSpan").style.display="inline";break;case "5":document.getElementById("scheduledMonthSpan").style.display=
"none";document.getElementById("scheduledDOMSpan").style.display="inline";document.getElementById("scheduledDOWSpan").style.display="none";document.getElementById("scheduledTimeSpan").style.display="inline";break;case "6":document.getElementById("scheduledMonthSpan").style.display="inline",document.getElementById("scheduledDOMSpan").style.display="inline",document.getElementById("scheduledDOWSpan").style.display="none",document.getElementById("scheduledTimeSpan").style.display="inline"}}
function emptyCheckVte(a,b,d){var e=getObj(a);if("text"==d){if(""==e.value||0==e.value.replace(/^\s+/g,"").replace(/\s+$/g,"").length){if("undefined"!=typeof jQuery("#s_"+a).val()&&""!=jQuery("#s_"+a).val())return!0;b={title:app.vtranslate(b+app.vtranslate("VAL_CANNOT_BE_EMPTY")),type:"error"};Vtiger_Helper_Js.showPnotify(b);try{e.focus()}catch(f){}return!1}}else if("textarea"==d&&"undefined"!==typeof CKEDITOR&&"undefined"!==CKEDITOR.intances[a]){if(e=CKEDITOR.intances[a].getData(),""==trim(e)||"<br>"==
trim(e))return alert(b+app.vtranslate("CANNOT_BE_NONE")),!1}else if(""==trim(e.value))return alert(b+app.vtranslate("CANNOT_BE_NONE")),!1;return!0}
function getFieldsOptionsSearch(a){a.value.toLowerCase();document.getElementById("primarymodule");document.getElementById("primarymodule");b=document.getElementById("availModValues").innerHTML;b=b.split("(!#_ID@ID_#!)");a=b[0];var b=b[2],d=document.getElementById("availModules").options[availModules.selectedIndex].value;if(a==d){a=b.split("(|@!@|)");for(i=0;i<a.length;i++)if(b=a[i].split("(|@|)"),""!=b[0]){document.createElement("OPTGROUP").label=b[0];var b=JSON.parse(b[1]),e;for(e in b)if(b.hasOwnProperty(e)){var f=
b[e],d=document.createElement("div");d.id=f.value;d.className="div_column_child div_column_child_off";var g=document.createElement("img");g.src="modules/VTEReports/img/check_ico.png";d.appendChild(g);g=document.createElement("p");f=document.createTextNode(f.text);g.appendChild(f);d.appendChild(g);document.getElementById("div_selected_column").appendChild(d)}}return!0}}
function getSUMFieldsOptionsSearch(a){a=a.value.toLowerCase();document.getElementById("primarymodule");document.getElementById("primarymodule");var b=document.getElementById("availSumModValues").innerHTML,d=b.split("(!#_ID@ID_#!)"),e=d[0],b=d[2],f=document.getElementById("SummariesModules"),d=SummariesModules.options[SummariesModules.selectedIndex].text;if(e==f.options[f.selectedIndex].value){document.getElementById("availListSum").innerHTML="";e=b.split("(|@!@|)");for(i=0;i<e.length;i++)if(f=e[i].split("(|@|)"),
""!=f[0]){b=document.createElement("OPTGROUP");b.label=d+" - "+f[0];var f=JSON.parse(f[1]),g;for(g in f)if(f.hasOwnProperty(g)){var h=f[g],k=h.text;if(-1<k.toLowerCase().indexOf(a)){var m=document.createElement("OPTION");m.value=h.value;m.appendChild(document.createTextNode(k));b.appendChild(m);0==i?document.getElementById("availListSum").appendChild(m):document.getElementById("availListSum").appendChild(b)}}}return!0}}
function getTLFieldsOptionsSearch(a){a=a.value.toLowerCase();var b=document.getElementById("avail_timeline_columns").value,b=JSON.parse(b);document.getElementById("timeline_columns").innerHTML="";for(var d in b)if(b.hasOwnProperty(d)){var e=document.createElement("OPTGROUP");e.label=d;for(var f in b[d])if(b[d].hasOwnProperty(f)){var g=b[d][f].text,h=b[d][f].value;if(-1<g.toLowerCase().indexOf(a)){var k=document.createElement("OPTION");k.value=h;k.appendChild(document.createTextNode(g));e.appendChild(k);
0==d?document.getElementById("timeline_columns").appendChild(k):document.getElementById("timeline_columns").appendChild(e)}}}return!0}function addOndblclick(a){(a.selectedIndex||0==a.selectedIndex)&&addColumn("selectedColumns")}function addOndblclickSUM(a){(a.selectedIndex||0==a.selectedIndex)&&addColumn("selectedSummaries")}function defineModuleFields(a){setModuleFields(a,"getStep5Columns")}function defineSUMModuleFields(a){setModuleFields(a,"getStep5SUMColumns")}
function setModuleFields(a,b){if("getStep5SUMColumns"==b)var d="search_input_sum",e="SummariesModules",f="Sum";else"getStep5Columns"==b&&(d="search_input",e="availModValues",f="");var g=a.options[a.selectedIndex].value;document.getElementById(e);document.getElementById(d).value="";d={selectedmodule:g,mode:b};d={type:"POST",url:"index.php?module=VTEReports&action=IndexAjax&primarymoduleid="+jQuery("#primarymodule").val(),dataType:"html",data:d};AppConnector.request(d).then(function(a){setAvailableFields(a,
f)})}function setStep5Columns(a){var b=JSON.parse(a[0]);a=a[1];var d=document.getElementById("availModules");d.innerHTML="";d.options.length=0;for(var e in b)if(b.hasOwnProperty(e)){var f=b[e],g=document.createElement("OPTION");g.value=f.id;"checked"==f.checked?(g.checked=!0,f=f.name):f="- "+f.name;g.appendChild(document.createTextNode(f));d.appendChild(g)}setAvailableFields(a,"")}
function setAvailableFields(a,b){var d=document.getElementById("availModValues");null!==d&&(d.innerHTML=a);var e=a.split("(!#_ID@ID_#!)"),d=e[0];a=e[2];var e=""!=b?document.getElementById("SummariesModules"):document.getElementById("availModules"),e=e.options[e.selectedIndex].value,f;""!=b&&(f=jQuery("#selectedSummariesTmp").val().split(";"),jQuery.each(f,function(a,b){var d=b.split("##$$##");f[a]=d[0]}));if(d==e)for(d=a.split("(|@!@|)"),i=0;i<d.length;i++){var g=d[i].split("(|@|)");if(""!=g[0]){e=
document.createElement("div");e.className="block_title_div";var h=g[0];""==b&&(h=h.substring(3));e.innerHTML='<p class="block_title_content">'+h+"</p>";var g=JSON.parse(g[1]),k;for(k in g)if(g.hasOwnProperty(k)){h=document.getElementById("div_selected_column");""==b&&(h=document.getElementById("div_list_fields_column"));var m=g[k];if(null===document.getElementById(m.value)){var l=document.createElement("div");l.id=m.value;var n=jQuery.inArray(m.value,f);0<=n?(f.splice(n,1),l.className="div_column_child div_column_child_on"):
l.className="div_column_child div_column_child_off";n=document.createElement("img");n.src="modules/VTEReports/img/check_ico.png";l.appendChild(n);var n=document.createElement("p"),p=document.createTextNode(m.text);n.appendChild(p);l.appendChild(n);e.appendChild(l);null===document.getElementById(m.value)&&h.appendChild(e)}}}}}function setAvailableSUMFields(a){setAvailableFields(a,"Sum")}
function checkEmptyLabel(a){document.getElementById(a)&&""==document.getElementById(a).value.trim()&&(document.getElementById(a).value=document.getElementById("hidden_"+a).value)}function escapeRegExp(a){return a.replace(/([.*+?^=!:${}()|\[\]\/\\])/g,"\\$1")}
function matrix_js(a){if(2==a)var b=a+1;else 3==a&&(b=a-1);var d=document.getElementById("timeline_type"+a),e=document.getElementById("timeline_type"+b);document.getElementById("Group"+a);document.getElementById("Group"+b);if(2==a&&"none"==jQuery("#Group"+b).val())return d.options[1].selected=!0,e.options[0].selected=!0,!1;if(3==a&&"none"==jQuery("#Group"+a).val())return d.options[0].selected=!0,e.options[1].selected=!0,!1;2==a?"cols"==jQuery("#timeline_type"+a).val()?jQuery("#timeline_type"+b).val("rows"):
jQuery("#timeline_type"+b).val("cols"):3==a&&("cols"==jQuery("#timeline_type"+a).val()?jQuery("#timeline_type"+b).val("rows"):jQuery("#timeline_type"+b).val("cols"))}
function checkTimeLineColumn(a,b){if(1<b){if("none"==document.getElementById("Group1").options[document.getElementById("Group1").selectedIndex].value)return alert(document.getElementById("Group1").name+app.vtranslate("CANNOT_BE_EMPTY")),a.options[0].selected=!0,!1;if("none"==document.getElementById("Group2").options[document.getElementById("Group2").selectedIndex].value)return alert(document.getElementById("Group2").name+app.vtranslate("CANNOT_BE_EMPTY")),a.options[0].selected=!0,!1}if(a){var d=a.options[a.selectedIndex].value;
if(document.getElementById("date_options_json")){var e=document.getElementById("date_options_json").innerHTML;console.log(e);e&&(0<JSON.stringify(e).indexOf(d)?(e=document.getElementById("timelinecolumn_html").value,e=replaceAll("@NMColStr","_Group"+b,e),e=replaceAll("value='","value='"+d,e),document.getElementById("radio_group"+b).innerHTML=e):0<d.indexOf(":D")?"cols"==jQuery("#timeline_type"+b).val()&&(e=document.getElementById("timelinecolumn_html").value,e=replaceAll("@NMColStr","_Group"+b,e),
document.getElementById("radio_group"+b).innerHTML=e):document.getElementById("radio_group"+b).innerHTML="")}}}function getGroupTimeLineValue(a){var b="";if(document.getElementsByName("TimeLineColumn_Group"+a)){a=document.getElementsByName("TimeLineColumn_Group"+a);for(var d=0,e=a.length;d<e;d++)if(a[d].checked){b=a[d].value;break}}return b}
function getGroupTimeLineType(a){var b="";document.getElementById("timeline_type"+a)&&(a=document.getElementById("timeline_type"+a),b=a.options[a.selectedIndex].value);return b}function getUpSelectedSharing(){var a="";if(document.getElementById("sharingSelectedColumns")){var b=document.getElementById("sharingSelectedColumns"),a="";for(i=0;i<=b.length-1;i++)a+=b[i].value+"|";document.getElementById("sharingSelectedColumnsString").value=a}return a}
function defineChartType(a){for(var b=a.options[a.selectedIndex],d=0;d<a.options.length;d++){var e=a.options[d].value+"_type";document.getElementById(e)&&(document.getElementById(e).style.display="none")}null!=b.value&&0!=b.value.length&&(e=b.value+"_type",setChartColumns(b),document.getElementById(e)&&(document.getElementById(e).style.display="block"))}
function setChartTitle(a){var b;if(null!==document.getElementById("chartType"))b=document.getElementById("chartType");else return!1;if("none"==b.options[b.selectedIndex].value)return!1;a&&""!=a.value&&document.getElementById("chart_title_div")&&(document.getElementById("chart_title_div").innerHTML=a.value)}function setChartColumns(a){if("pie"==a||"funnel"==a)document.getElementById("ycols").innerHTML="&nbsp",document.getElementById("xcols").innerHTML="&nbsp"}
function VTEReportsDateValidate(a,b,d){if(0==patternValidate(a,b,"DATE"))return!1;var e=getObj(a).value.replace(/^\s+/g,"").replace(/\s+$/g,""),f=splitDateVal(e),e=f[0],g=f[1],f=f[2];if(1>e||31<e||1>g||12<g||1>f||1E3>f){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(m){}return!1}if(2==g&&29<e){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(m){}return!1}if(2==g&&28<e&&0!=f%4){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(m){}return!1}switch(parseInt(g)){case 2:case 4:case 6:case 9:case 11:if(30<
e){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(m){}return!1}}var h=new Date,k=new Date;k.setYear(f);k.setMonth(g-1);k.setDate(e);if("OTH"!=d){if(compareDates(k,b,h,"current date",d))return!0;try{getObj(a).focus()}catch(m){}return!1}return!0}
function VTEReportsre_dateValidate(a,b,d){if(0==re_patternValidate(a,b,"DATE"))return!1;a=a.replace(/^\s+/g,"").replace(/\s+$/g,"");var e=splitDateVal(a);a=e[0];var f=e[1],e=e[2];if(1>a||31<a||1>f||12<f||1>e||1E3>e||2==f&&29<a||2==f&&28<a&&0!=e%4)return alert(app.vtranslate("ENTER_VALID")+b),!1;switch(parseInt(f)){case 2:case 4:case 6:case 9:case 11:if(30<a)return alert(app.vtranslate("ENTER_VALID")+b),!1}var g=new Date,h=new Date;h.setYear(e);h.setMonth(f-1);h.setDate(a);return"OTH"!=d?compareDates(h,
b,g,"current date",d)?!0:!1:!0}function VTEReportsStDateValidate(a,b,d){if("undefined"!=typeof document.getElementById("jscal_field_sdate"+a)&&"undefined"!=typeof document.getElementById("jscal_field_edate"+a))switch(b){case "custom":if(!emptyCheckVte("jscal_field_sdate"+a,d,"date")||!emptyCheckVte("jscal_field_edate"+a,d,"date"))return!1}return!0}function setSelectedCriteriaValue(a,b){for(var d=0;d<a.options.length;d++)a.options[d].value==b&&(a.options[d].selected=!0)}
function SaveChartImg(a,b){document.getElementById("current_action")&&document.getElementById("current_action");window.open("index.php?module=VTEReports&action=IndexAjax&mode=DownloadFile&filepath="+a+"&filename="+b+".png",b,"width=20,height=20");return!0}
function generatePDF(a,b,d,e){if(1==b||1==b){if((a=document.getElementById("report_filename"))&&""!=a.value)return exportToPDF(a.value),!0;document.getElementById(e).style.display="block";return!1}document.getElementById(e).style.display="block";return!1}
function printDiv(){var a=document.getElementById("vtereports_html").innerHTML;w=window.open();w.document.write(a);w.document.write('<script type="text/javascript">window.onload = function() { window.print(); window.close(); };\x3c/script>');w.document.close();w.focus();return!0}function getReportRecordID(){return"Edit"==jQuery("#view").val()?document.NewReport.record.value:jQuery("#recordId").val()}
function numValidate(a,b,d,e){var f=getObj(a).value.replace(/^\s+/g,"").replace(/\s+$/g,"");if("undefined"!=typeof userCurrencySeparator&&""!=userCurrencySeparator)for(;-1!=f.indexOf(userCurrencySeparator);)f=f.replace(userCurrencySeparator,"");"undefined"!=typeof userDecimalSeparator&&""!=userDecimalSeparator&&-1!=f.indexOf(userDecimalSeparator)&&(f=f.replace(userDecimalSeparator,"."));if("any"!=d){if(isNaN(f))var g=!0;else{d=d.split(",");var h=f.split(".");1==e?0<=h[0].indexOf("-")?h[0].length-
1>d[0]&&(g=!0):h[0].length>d[0]&&(g=!0):0>f?g=!0:2!=d[0]||100!=h[0]||h[1]&&0!=h[1]?h[0].length>d[0]&&(g=!0):g=!1;h[1]&&h[1].length>d[1]&&(g=!0)}if(1==g){alert(app.vtranslate("INVALID")+b);try{getObj(a).focus()}catch(k){}return!1}return!0}if("probability"==a||"commissionrate"==a){f=getObj(a).value.replace(/^\s+/g,"").replace(/\s+$/g,"");h=f.split(".");d=0;1<h.length&&(d=h[1].length);if(isNaN(f)){alert(app.vtranslate("INVALID")+b);try{getObj(a).focus()}catch(k){}return!1}if(100<h[0]||3<d||100<=h[0]&&
0<h[1])return alert(b+app.vtranslate("EXCEEDS_MAX")),!1}else if(h=f.split("."),1.8446744073709552E19<h[0])return alert(b+app.vtranslate("EXCEEDS_MAX")),!1;e=1==e?/^(-|)(\d)*(\.)?\d+(\.\d\d*)*$/:/^(\d)*(\.)?\d+(\.\d\d*)*$/;for(d=h=0;d<f.length;d++)"."==f.charAt(d)&&h++;if(1<h){alert(app.vtranslate("INVALID")+b);try{getObj(a).focus()}catch(k){}return!1}if(e.test(f))return!0;alert(app.vtranslate("INVALID")+b);try{getObj(a).focus()}catch(k){}return!1}
function intValidate(a,b){var d=getObj(a).value.replace(/^\s+/g,"").replace(/\s+$/g,"");if("undefined"!=typeof userCurrencySeparator&&""!=userCurrencySeparator)for(;-1!=d.indexOf(userCurrencySeparator);)d=d.replace(userCurrencySeparator,"");if(isNaN(d)||-1!=d.indexOf(".")&&"potential_amount"!=a&&"list_price"!=a){alert(app.vtranslate("INVALID")+b);try{getObj(a).focus()}catch(e){}return!1}if("employees"==a&&"noofemployees"==a||!(-2147483648>d||2147483647<d)){if("employees"!=a&&"noofemployees"==a||!(0>
d||2147483647<d))return!0;alert(b+app.vtranslate("OUT_OF_RANGE"));return!1}alert(b+app.vtranslate("OUT_OF_RANGE"));return!1}
function dateValidate(a,b,d){if(0==patternValidate(a,b,"DATE"))return!1;dateval=getObj(a).value.replace(/^\s+/g,"").replace(/\s+$/g,"");var e=splitDateVal(dateval);dd=e[0];mm=e[1];yyyy=e[2];if(1>dd||31<dd||1>mm||12<mm||1>yyyy||1E3>yyyy){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(g){}return!1}if(2==mm&&29<dd){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(g){}return!1}if(2==mm&&28<dd&&0!=yyyy%4){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(g){}return!1}switch(parseInt(mm)){case 2:case 4:case 6:case 9:case 11:if(30<
dd){alert(app.vtranslate("ENTER_VALID")+b);try{getObj(a).focus()}catch(g){}return!1}}var e=new Date,f=new Date;f.setYear(yyyy);f.setMonth(mm-1);f.setDate(dd);if("OTH"!=d){if(compareDates(f,b,e,"current date",d))return!0;try{getObj(a).focus()}catch(g){}return!1}return!0}
function re_dateValidate(a,b,d){if(0==re_patternValidate(a,b,"DATE"))return!1;dateval=a.replace(/^\s+/g,"").replace(/\s+$/g,"");a=splitDateVal(dateval);dd=a[0];mm=a[1];yyyy=a[2];if(1>dd||31<dd||1>mm||12<mm||1>yyyy||1E3>yyyy||2==mm&&29<dd||2==mm&&28<dd&&0!=yyyy%4)return alert(app.vtranslate("ENTER_VALID")+b),!1;switch(parseInt(mm)){case 2:case 4:case 6:case 9:case 11:if(30<dd)return alert(app.vtranslate("ENTER_VALID")+b),!1}a=new Date;var e=new Date;e.setYear(yyyy);e.setMonth(mm-1);e.setDate(dd);return"OTH"!=
d?compareDates(e,b,a,"current date",d)?!0:!1:!0}
function re_patternValidate(a,b,d){if("EMAIL"==d.toUpperCase())var e=new RegExp(/^[a-zA-Z0-9]+([\_\-\.]*[a-zA-Z0-9]+[\_\-]?)*@[a-zA-Z0-9]+([\_\-]?[a-zA-Z0-9]+)*\.+([\-\_]?[a-zA-Z0-9])+(\.?[a-zA-Z0-9]+)*$/);if("DATE"==d.toUpperCase())switch(userDateFormat){case "yyyy-mm-dd":e=/^\d{4}(-)\d{1,2}\1\d{1,2}$/;break;case "mm-dd-yyyy":case "dd-mm-yyyy":e=/^\d{1,2}(-)\d{1,2}\1\d{4}$/}"TIMESECONDS"==d.toUpperCase()&&(e=/^([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9])$|^([0-1][0-9]|[2][0-3]):([0-5][0-9])$/);if(e.test(a))return!0;
alert(app.vtranslate("ENTER_VALID")+b);return!1}
function patternValidate(a,b,d){a=getObj(a);if("EMAIL"==d.toUpperCase())var e=new RegExp(/^[a-zA-Z0-9]+([!"#$%&'()*+,./:;<=>?@\^_`{|}~-]?[a-zA-Z0-9])*@[a-zA-Z0-9]+([\_\-\.]?[a-zA-Z0-9]+)*\.([\-\_]?[a-zA-Z0-9])+(\.?[a-zA-Z0-9]+)?$/);if("DATE"==d.toUpperCase())switch(userDateFormat){case "yyyy-mm-dd":e=/^\d{4}(\-|\/|\.)\d{1,2}\1\d{1,2}$/;break;case "mm-dd-yyyy":case "dd-mm-yyyy":e=/^\d{1,2}(\-|\/|\.)\d{1,2}\1\d{4}$/}"TIME"==d.toUpperCase()&&(e=/^\d{1,2}\:\d{2}:\d{2}$|^\d{1,2}\:\d{2}$/);if("EMAIL"==
d.toUpperCase()||"DATE"==d.toUpperCase())a.value=trim(a.value);if(e.test(a.value))return!0;alert(app.vtranslate("ENTER_VALID")+b+" ("+d+")");try{a.focus()}catch(f){}return!1}
function ChartDataSeries(a){a=a.options[a.selectedIndex];"undefined"!=typeof a&&("group2"==a.value?(jQuery("#data_series2").val(""),jQuery("#chartType2").val(""),jQuery("#chartType2").attr("disabled","true"),jQuery("#data_series2").attr("disabled","true"),jQuery("#data_series3").val(""),jQuery("#chartType3").val(""),jQuery("#chartType3").attr("disabled","true"),jQuery("#data_series3").attr("disabled","true")):(jQuery("#chartType2").attr("disabled","false"),jQuery("#chartType2").removeAttr("disabled"),
jQuery("#data_series2").attr("disabled","false"),jQuery("#data_series2").removeAttr("disabled"),jQuery("#chartType3").attr("disabled","false"),jQuery("#chartType3").removeAttr("disabled"),jQuery("#data_series3").attr("disabled","false"),jQuery("#data_series3").removeAttr("disabled")))}
function saveChartImageToFile(a,b,d,e){var f="test/VTEReports/"+d+".png";AppConnector.request({type:"POST",url:"index.php?module=VTEReports&action=SaveImage",dataType:"html",data:{filename:d,report_filename:b,filepath:f,export_pdf_format:a,canvasData:e}}).then(function(d){window.open("index.php?module=VTEReports&action=SaveImage&mode=download&export_pdf_format="+a+"&report_filename="+b+"&filepath="+f,"_blank")})}
function saveChartAsBinary(){var a=jQuery("#recordId").val(),b=jQuery("#export_pdf_format").val(),d=jQuery("#pdf_file_name").val(),e=jQuery("#ch_image_name").val(),a=document.getElementById("vtereports_widget_"+a).children[0].innerHTML;canvg(document.getElementById("canvas"),a);a=canvas.toDataURL("image/png");a=a.replace("data:image/png;base64,","");saveChartImageToFile(b,d,e,a)}
function exportToPDF(a){var b;jQuery("#export_pdf_format").val();var d=jQuery(".vteTableText").html(),e=jQuery("#vtereports_html").html(),f=jQuery("#recordId").val();b=jQuery("#export_pdf_format").val();var g="";null!=document.getElementById("vtereports_widget_"+f)&&(jQuery("#ch_image_name").val(),f=document.getElementById("vtereports_widget_"+f).children[0].innerHTML,canvg(document.getElementById("canvas"),f),g=canvas.toDataURL("image/png"),g=g.replace("data:image/png;base64,",""));jQuery("#form_export_pdf_format").val(b);
jQuery("#form_filename").val(a);jQuery("#form_report_name").val(d);jQuery("#form_report_html").val(e);jQuery("#form_chart_canvas").val(g);jQuery("#CreatePDF").submit();return!1};